version: '3.8'

services:
  # 开发环境
  frontend-dev:
    build:
      context: .
      target: development
    container_name: frontend-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://47.86.184.188:8000
      - VITE_API_TIMEOUT=30000
      - NPM_CONFIG_FUND=false
      - NPM_CONFIG_AUDIT=false
    command: sh -c "npm run dev -- --host 0.0.0.0"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

