version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./sql_app.db
      # 添加其他环境变量
      - MAX_WORKERS=2  # 限制 worker 数量
      - WORKER_CLASS=uvicorn.workers.UvicornWorker
      - LOG_LEVEL=warning
    volumes:
      - ./sql_app.db:/app/sql_app.db
      - ./logs:/app/logs  # 日志持久化
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G  # 限制内存使用
        reservations:
          memory: 512M  # 预留内存
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 